### ISSUE TITLE
Not working with ModelMetaDataType Attribute

### ISSUE THREAD

**Issue by gauravsingh8026** [topnguyen/Elect#8] opened 2020-05-31 14:57 UTC
I am using Elect.Web.DataTable to generate datatable response.

I have a ef core generated class like this

```
public partial class Employee
{
       public Employee()
        {
            EmpSalary = new HashSet<EmpSalary>();
            Loan = new HashSet<Loan>();
            PfContribution = new HashSet<PfContribution>();
        }
        public long EmpId { get; set; }

        public string EmpFirstName { get; set; }
        
        public string EmpLastName { get; set; }
        
        public string EmpStreet { get; set; }
        
        public string EmpCity { get; set; }
}
```

And decorated properties of this class like this

```
[ModelMetadataType(typeof(IEmployeeMetadata))]
    public partial class Employee :IEmployeeMetadata
    {
        [DataTable(DisplayName = "Name")]
        public string FullName { get { return this.EmpFirstName + " " + this.EmpLastName; } }
    }

    public interface IEmployeeMetadata
    {
        [DataTable(IsVisible = false)]
        long EmpId { get; set; }

        [DataTable(DisplayName = " First Name")]
        [DisplayName("First Name")]
        string EmpFirstName { get; set; }
    }
```

DisplayName attribute on property "EmpFirstName" works good on view page with `@Html.EditorFor`, but DataTable attributes are not working.

**Comment by topnguyen** [comment] 2020-06-01 02:40
Hi @gauravsingh8026,

The library Elect.Web.Datatable is Server generate jQuery DataTable.

So it just supports for generate the jQuery DataTable, not support to use on Form as `@Html.EditorFor`

You can check the [Example here](https://github.com/topnguyen/Elect/blob/master/samples/Web/Elect.Sample.Web.DataTable/README.md) for more detail

**Comment by gauravsingh8026** [comment] 2020-06-01 07:30
Sorry, You didn't understand my problem. 
My problem is with `[DataTable(DisplayName="First Name")]` attribute for property `string EmpFirstName { get; set; }` defined in the interface *IEmployeeMetadata*.

This should generate column name **First Name** for property **EmpFirstName**, But its not working.

Actual Output

EmpId  | <ins>EmpFirstName</ins> | EmpLastName | EmpStreet | EmpCity 
-------- | ---------------- | ----------------| ------------| ---------
1 | Gaurav | Singh | street1 | city1

Expected Output

EmpId  | <ins>First Name</ins> | EmpLastName | EmpStreet | EmpCity 
-------- | ---------------- | ----------------| ------------| ---------
1 | Gaurav | Singh | street1 | city1

**Comment by topnguyen** [comment] 2020-06-01 07:36
Hi @gauravsingh8026 ,

Thank you for your clarification.

Let me try to re-procedure the issue on my local machine, I will get back to you soon.

**Comment by topnguyen** [comment] 2020-06-01 08:52
Hi @gauravsingh8026 

The issue is the Elect.Web.DataTable only read the attribute `DataTable` directly on the property of `Class`, not `Interface`.

So your `Entity` need to add the attribute `[DataTable(DisplayName = " First Name")]` to make it work.

I will find out a way to we can use the `DataTable` attribute on the property in `Interface` and a way to resolve conflict if we face `DataTable` attribute on both `Class` and `Interface`.

**Comment by topnguyen** [comment] 2020-06-01 09:12
Hi @gauravsingh8026 ,

I have updated lib to ver 3.0.5 to support read the `DataTable` attribute from Interface (just the first interface found matched property) as your case.

Please checking https://www.nuget.org/packages/Elect.Web.DataTable/3.0.5 (need time for nugget.org index it)
or you can check my nugget server http://nuget.topnguyen.com/packages/Elect.Web.DataTable

Please let me know if the issue gone or you need more help.

**Comment by gauravsingh8026** [comment] 2020-06-01 09:27
Thanks @topnguyen 

Yes, Issue is fixed in this update, and nugget has indexed it also.
Just one more help, is there any way to reorder generated columns positions. Properties defined in interface are now at the end of the output table.

Thanks again for this awesome library.

**Comment by topnguyen** [comment] 2020-06-01 09:41
Hi @gauravsingh8026 ,

You can define the order by `Order` value in `DataTable` attribute.

You can refer this example https://github.com/topnguyen/Elect/blob/master/samples/Web/Elect.Sample.Web.DataTable/Models/UserModel.cs

**Comment by topnguyen** [comment] 2020-06-01 11:27
I would like to close this ticket due to the issue fixed.

Feel free to re-open if the issue comeback.

**Closed by topnguyen** 2020-06-01 11:27 UTC

**Comment by gauravsingh8026** [comment] 2020-06-01 12:37
Thank you for the help @topnguyen

**Comment by gauravsingh8026** [comment] 2020-06-01 13:15
Hi @topnguyen 

There is another issue now, `DataTableIgnore` attribute from Interface has no effect on output Datatable

**Comment by topnguyen** [comment] 2020-06-01 13:32
Hi @gauravsingh8026 ,

I have uploaded ver https://www.nuget.org/packages/Elect.Web.DataTable/3.0.5.1 to handle the `DataTableIgnore` attribute in Interface as well.

Please keep in mind that the Attribute in Interface only apply if there are not have any `DataTable` attribute on `Property` of the `Class`

I have tested and updated the Sample as well https://github.com/topnguyen/Elect/blob/master/samples/Web/Elect.Sample.Web.DataTable/Models/UserModel.cs

**Comment by gauravsingh8026** [comment] 2020-06-01 14:24
Sorry @topnguyen, `DataTableIgnore` still not working with interface

Here is the link of class and interface file, if you want to check.
https://github.com/gauravsingh8026/ElectDataTableIssue/blob/master/Models/Employee.cs
https://github.com/gauravsingh8026/ElectDataTableIssue/blob/master/ModelsExtended/Employee.cs

**Comment by topnguyen** [comment] 2020-06-01 14:40
Hi @gauravsingh8026 , I fixed the issue in ver https://www.nuget.org/packages/Elect.Web.DataTable/3.0.5.2

My mistake on checking the Attribute.

**Comment by gauravsingh8026** [comment] 2020-06-01 14:52
Looks good now.

Thanks for the help 👍
